# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-24 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, b'Hotel'), (2, b'Campsite'), (3, b'Field'), (4, b'Bed and Breakfast'), (5, b'Hotel Garni'), (6, b'Pension'), (7, b'Holiday Cottage'), (8, b'Youth Hostel'), (9, b'Bunkhouse')])),
                ('name', models.CharField(max_length=1001)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('short_name', models.CharField(blank=True, max_length=1001)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=60, help_text=b'minutes')),
                ('preferred_days', models.IntegerField(blank=True, choices=[(1, b'Sunday'), (2, b'Monday'), (4, b'Tuesday'), (8, b'Wednesday'), (16, b'Thursday'), (32, b'Friday'), (64, b'Saturday')], null=True)),
                ('activity_type', models.IntegerField(choices=[(1, b'Workshop'), (2, b'Excursion'), (3, b'Lecture'), (4, b'Community Activity'), (5, b'Hike'), (6, b'Run')], default=1)),
                ('attachment', models.FileField(null=True, upload_to=b'attachments/')),
                ('attachment_type', models.IntegerField(choices=[(1, b'GPS Track'), (2, b'Image'), (3, b'Data')], default=3)),
                ('attendees', models.ManyToManyField(blank=True, editable=False, related_name='activity_attendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Lbw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, choices=[(1, b'Full fat'), (2, b'Mini'), (3, b'Micro'), (4, b'One man alone in a bar'), (5, b'Kriek')], default=1, null=True)),
                ('description', models.TextField()),
                ('short_name', models.CharField(max_length=1001)),
                ('start_date', models.DateTimeField(help_text=b'Format: YYYY-MMM-DD HH:MM:SS')),
                ('end_date', models.DateTimeField(help_text=b'Format: YYYY-MMM-DD HH:MM:SS')),
                ('location', models.CharField(blank=True, max_length=1001)),
                ('lbw_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=1001)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Activity')),
                ('lbw', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Lbw')),
                ('next', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_message', to='registration.Message')),
                ('previous', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_message', to='registration.Message')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_from', models.CharField(max_length=1001)),
                ('ride_to', models.CharField(max_length=1001)),
                ('notes', models.CharField(max_length=1001)),
                ('lbw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Lbw')),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offerer', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1001)),
                ('picture', models.CharField(max_length=401)),
                ('price', models.IntegerField()),
                ('lbw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Lbw')),
            ],
        ),
        migrations.CreateModel(
            name='TshirtOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(choices=[(b'M - S', b'Men - Small'), (b'M - M', b'Men - Medium'), (b'M - L', b'Men - Large'), (b'M - XL', b'Men - Large')], max_length=51)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Tshirt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(help_text=b'Format: YYYY-MMM-DD HH:MM:SS')),
                ('departure_date', models.DateTimeField(help_text=b'Format: YYYY-MMM-DD HH:MM:SS')),
                ('children', models.IntegerField(default=0)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Accommodation')),
                ('lbw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Lbw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lbw',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='lbw_attendees', through='registration.UserRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lbw',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='lbw_owners', to='accounts.LbwUser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lbw',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='registration.Lbw'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='activity_owners', to='accounts.LbwUser'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='lbw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Lbw'),
        ),
    ]
